/* eslint-disable max-lines */
// AUTO-GENERATED from CATALOGUE LIST.xlsx. Do not edit by hand.
// Regenerate: node scripts/extract-catalogues-seed.mjs

import type { ProductFamily } from "@prisma/client";

export const CATALOGUE_SEED: ReadonlyArray<{ family: ProductFamily; names: readonly string[] }> = [
  {
    family: "WALLPAPER",
    names: [
      "1001 NIGHTS",
      "ABACA",
      "AFFINITY",
      "ALBANY",
      "ALLURING",
      "ALTA GAMMA - EVOLUTION",
      "ALTA GAMMA - LIVING",
      "ALTA GAMMA - TISSE",
      "ALTA GAMMA-HOME 3",
      "ALTA GAMMA-WOVEN",
      "AMAZONE",
      "AMAZONIA",
      "AMIGO",
      "ANCIENT ECRYPT",
      "ANITA",
      "ANTIBES",
      "ARCA",
      "ART BOOK VOL-2",
      "ART DECO",
      "ARTISIAN",
      "ARTIST",
      "ASPERIA",
      "ASTRA",
      "ATLANTA",
      "ATMOSPHERE",
      "ATTITUDE",
      "AURORA",
      "AURORA VOL 2",
      "AVANT",
      "B-SPOKE",
      "BESTIE",
      "BEYOND",
      "BLISS",
      "BORD DU NIL",
      "BRAHMOS",
      "CABINET",
      "CANVAS",
      "CARL-ROBINSON",
      "CARMEN",
      "CARMEN 2",
      "CARRARA",
      "CASABLANCA",
      "CASAD",
      "CASAMOOD",
      "CERAME",
      "CHELSEA",
      "CHROMA",
      "CIARA",
      "CLASSY",
      "COLOUR LINE -1",
      "COLOUR LINE -2",
      "CONTRACT",
      "CORK & MICA",
      "CRYSTAL",
      "CUMARU",
      "D&D",
      "DARAE",
      "DECENT",
      "DESIGNTEX",
      "DIVINO",
      "DREAM LAND",
      "DUBAI",
      "E-JOY 7",
      "ECEDECO ESSENTIALS",
      "ECO PROJECT -VOL 10",
      "ELDOREDO",
      "ELEMENT 79",
      "ELEMENTO",
      "ELEMENTS 5",
      "ELEVATE",
      "EMIL & HUGO PLAINS",
      "ENRICH",
      "ESSEN",
      "ETHINIC BY LEGENDS",
      "EYNA",
      "FABRICA",
      "FAGELSANG",
      "FAITH",
      "FALCON",
      "FAUNA",
      "FEEL",
      "FEELALA",
      "FELICITY",
      "FESTA",
      "FLASH",
      "FLORINA",
      "FUN TIME",
      "FUN TIME 2",
      "FUN ZONE",
      "GEMS 2",
      "GLEAM",
      "GLIMMER",
      "GOLDEN HOUR",
      "GRACE",
      "GRACEFUL",
      "GRAVITY",
      "HAMILTON 2",
      "HAPPY",
      "HASHTAG",
      "HYPE",
      "ICONIC WALLS",
      "INDIA FUSION",
      "INDIAN JUNGLE FEVER",
      "INDIAN STYLE",
      "INDULGENEE",
      "INSPIRE",
      "J WALL - STRAW",
      "J WALL-REFLEX",
      "JAIPUR",
      "JOINUS",
      "JOURNEY TO THE EAST",
      "JUPITER",
      "JUTE & CANE",
      "JV 171 IKAT",
      "JV 181 LRMURHA",
      "KALAKRITI",
      "KARUNA",
      "KIDS & TEENS",
      "KYOTO",
      "KYRA",
      "LASER 2",
      "LAVISH",
      "LEVEL 2",
      "LIGHT",
      "LINARES",
      "LIVING",
      "LUCIDO",
      "LUSTRE",
      "LUX",
      "LUXERIA",
      "LUXOR",
      "LUXORA",
      "MACAU",
      "MAGNUM",
      "MARS",
      "MAYA",
      "MEDINA",
      "METABENE",
      "METALLIX",
      "METROPOLIS",
      "METTALIC WALLS",
      "MEWAR",
      "MIRACLE",
      "MIRAGE 7",
      "MISSION HOME 2",
      "MISSION HOME 3",
      "MODELICA",
      "MODERN ART",
      "MODERNA -ARTISAN",
      "MOTIVE",
      "MUNICH",
      "MUSE",
      "NATTE",
      "NATURAL",
      "NEO GEOMENTRIC",
      "NEST",
      "NIRVANA - CALM",
      "NIRVANA - SERENE",
      "NOBLE ZEN",
      "NOMAD",
      "NUEVO",
      "ONYX",
      "OPAL",
      "ORGANIC",
      "ORNAMENTS",
      "ORNELLA",
      "OROM 2",
      "PARADIZO",
      "PARISIAN TALES",
      "PATAGONIA",
      "PEARL",
      "PERFECT HARMONY",
      "PHOENIX",
      "PISTOLA",
      "PLATO",
      "PRECIOUS",
      "PRECIOUS WEAVES",
      "PRIMUS",
      "PROMISE",
      "PROTOFINA",
      "PUE+",
      "RAKU",
      "REFLECT",
      "REGAL",
      "REYNA",
      "ROMANCE",
      "SANSKRITI",
      "SANSKRITI 2",
      "SANSKRITI-TAVVA",
      "SATURN",
      "SAVOY",
      "SEABOOK DESINGN",
      "SECRET GARDEN",
      "SERENITY",
      "SERICA",
      "SHIMMER",
      "SIGNATURE 2",
      "SILVER MOON",
      "SIOE CHANGEANTE",
      "SLOW LIVING",
      "SMAASH",
      "SOLEADO",
      "SPRIT OF NATURE",
      "SQUARE GARDEN",
      "STYLE",
      "SUMMER",
      "SUPERB",
      "SYMPHONY",
      "TAHITI",
      "TALES OF THE MANOR",
      "TANISHQ",
      "TEMPO",
      "TEMPTATION",
      "TERRA ROSSA",
      "TESORO",
      "TEXTURA",
      "TEXTURE 2",
      "TEXTURED VIBES",
      "TEXTURED VIBES-STOCKING",
      "THEMA",
      "THEME",
      "TIME",
      "TORONTO",
      "TOUCH",
      "TOVO",
      "TRACES",
      "TRENDY SHADES",
      "TRIANON 8",
      "TRIBUTE",
      "TRUFFLE",
      "TULA",
      "UNIQUE",
      "UNIVERSE 3",
      "URBAN CLASSICS",
      "UTOPIE",
      "V CONCEPT",
      "VALENTIN YUDASHKIN",
      "VERA",
      "VIBE",
      "VIRTU",
      "VOYAGE",
      "WALL INDEX (VINYL WALL COVERING",
      "WALL SPARKLE",
      "WALL STAR 2",
      "WALL STAR 3",
      "WALL STAR 4",
      "WALL STAR 5",
      "WALL TEXTURES XL VOL 3",
      "WALL TRENDS",
      "WALL-FAB",
      "WAVE",
      "WHITE & GOLD",
      "WICKER & RAFFIA",
      "WONDER WALLS",
      "XTREME 2",
      "YUUMA",
      "ZEN",
      "ZIRCON",
    ],
  },
  {
    family: "MURAL",
    names: [
      "ALLURE",
      "AUTOGRAPH",
      "CONCETTO",
      "IMPRESSA",
      "IMPRESSA 2",
      "INDIA FUSION",
      "KRSNA MEHTA/SIGNATURE",
      "LANDSCAPE",
      "LIVING SOUL",
      "LUXORA - METTALIC WALLS",
      "LUXORA - METTALIC WALLS VOL 2",
      "LUXORA - METTALIC WALLS VOL 3",
      "LUXORA - METTALIC WALLS VOL 4",
      "MUNCHI",
      "MUNCHI VOL 1",
      "MUNCHI VOL 2",
      "MYSTIKA",
      "PARADISE",
      "PRAKRITI",
      "PURPLE TURTLE",
      "SEASONS",
      "SIGNATURE",
      "THE ARTIST",
      "XPERIA",
      "YOUNIQUE",
    ],
  },
  {
    family: "CURTAIN_FABRIC",
    names: [
      "AADHIRA",
      "AAISHA",
      "AAKRITI",
      "AALIA",
      "AARAMBH",
      "ABN TEXTURA DIMOUNT",
      "ALEENA",
      "ANCIENT 15",
      "ANCIENT 25",
      "ANDAAZ",
      "ANVIENT 30",
      "ASHLEY",
      "BASIC (BLACKOUT)",
      "BASIC SHEER-2",
      "BEADS",
      "BEST FOILS",
      "BLACK OUT",
      "BLACK OUT 100%",
      "BLUEBERRY COLLECTION",
      "BOTANICA CURTAIN",
      "BREEZE",
      "BRISK",
      "CANVAS",
      "CARTER",
      "DARPERY TEXTURES",
      "DARPERY TEXTURES 23",
      "DARPERY TEXTURES 3",
      "DARPERY TEXTURES 4",
      "DARPERY TEXTURES 5",
      "DEFENDER",
      "DENIM",
      "DIMOUT TEXTURES",
      "DUSK",
      "DYNASTY SHEERS",
      "EDITION",
      "ELYSIAN GARDEN",
      "EPILLANCE",
      "FABLE",
      "FIBER ARTISTRY VOL 2",
      "FIBER ARTISTRY VOL I",
      "FLAIR",
      "FLORANCE",
      "FOIL FESTINA",
      "FOIL KING",
      "GLAM",
      "GLOBUS COLLECTION",
      "GRAND",
      "HERITAGE PLAINS 1",
      "HERITAGE PLAINS 2",
      "HILTON 14",
      "HOTSTAR COLLECTION",
      "ICONIC",
      "JACKPOT 1",
      "JACKPOT 2",
      "JACQUARD TEXTURE 3",
      "JACQUARD TEXTURE 4",
      "JACQUARD TEXTURE 5",
      "JAZZ",
      "JING",
      "KAI PRINTS VOL.1",
      "KAI PRINTS VOL.2",
      "KIDS PRINT",
      "KONTRAST 2",
      "KOTTN",
      "KRAFTS",
      "LAOS",
      "LE-LIN 2",
      "LINEDN LOOK",
      "LINEN 5",
      "LINEN PRINT",
      "MAGIC 1114",
      "MANADE",
      "MARIA JACQUARDS",
      "MARKOVA CURTAINS",
      "MASCOT COLLECTION",
      "METALLICA",
      "MIST",
      "MOGUL",
      "MORVI CURTAINS",
      "NEOMA",
      "NOIR",
      "OPTIMA",
      "ORBIT",
      "ORIGIN COLLECTION 3",
      "ORRY",
      "PALMA",
      "PLUM",
      "PURE",
      "RANGREZ",
      "ROCAILLE TEXTURES",
      "ROCAILLE WEAVERS 1",
      "ROCAILLE WEAVERS 2",
      "ROCKERS",
      "ROLEX",
      "ROYAL 2",
      "ROYAL 3",
      "SAANJH",
      "SALSA",
      "SAVVY",
      "SEASONS",
      "SEDIMENT 2",
      "SELECT 3",
      "SHEER DREAMZ II",
      "SHEER FLOW",
      "SHIMMER",
      "SIENNA",
      "SILK ROUTE",
      "SILKEN",
      "SILKEN ROOTS",
      "SILKET",
      "SILVER OAK-2",
      "SILVER-OAK",
      "SIRSA",
      "SISLEY TEXTURES",
      "SKY ROCK",
      "SKYRAA II",
      "SKYWAY",
      "SLEEK",
      "SMARSH",
      "SMART CHOICE",
      "SMART CHOICE 1",
      "SMART CHOICE 2",
      "SOURCE",
      "SPERA",
      "SPRINGDALE",
      "SPRIT",
      "SRSHTI",
      "SRSHTI EKAM",
      "STARK",
      "STARLET",
      "STATUS",
      "SUNBLOCK(BLACKOUT)",
      "SUNDARBANS VOL 1",
      "SUNDARBANS VOL 2",
      "SUPRENO",
      "SYMPHONY VOL 2",
      "TEXTURES",
      "TOPSELLER COLLECTION",
      "TWILIGHT 100% BLACKOUT",
      "UNIVERSE 1",
      "UNIVERSE 2",
      "UNIVERSE 3",
      "V3 HOMES ENZO BLACKOUT",
      "VAAYU",
      "VANN",
      "VOUGE",
      "VYOM",
      "WEAVERS 1",
      "WILDWOOD TEXTURES",
      "WINDSOR",
      "ZARA 7 100%BLACKOUT",
      "ZYNNA -MB 3",
      "ZYNNA -MB 4",
      "ZYNNA -MB 7",
      "ZYNNA BB 05",
      "ZYNNA BB 06",
      "ZYNNA BB 08",
      "ZYNNA BB 10",
      "ZYNNA BB 11",
      "ZYNNA BB 12",
      "ZYNNA BB7",
      "ZYNNA MB6",
    ],
  },
  {
    family: "SHEER",
    names: [
      "AMBERLEY",
      "ATMOSPHERE",
      "AYYUR SHEERS",
      "COUNTRY SHEERS 10",
      "COUNTRY SHEERS 11",
      "COUNTRY SHEERS 12",
      "COUNTRY SHEERS 9",
      "DEMURE",
      "DESTINY 2",
      "DESTINY 3",
      "DOPE",
      "ENTWINE SHEERS 1",
      "ENTWINE SHEERS 2",
      "GRACE SHEERS",
      "LINEN EMBROIDERY",
      "MARINA SHEERS",
      "MELANGE",
      "NATURE SHEERS",
      "NIMMI 1",
      "NIMMI2",
      "ORCHID",
      "SAROVA III",
      "SHEER LOUNGE",
      "TAMARA",
      "VIBRANT 16",
      "VIBRANT 8",
      "ZARA 52",
    ],
  },
  {
    family: "UPHOLSTERY_FABRIC",
    names: [
      "AARAN",
      "ADORN",
      "ALPHABET",
      "ANTILLES",
      "AROMA PLAINS 2",
      "AROMA PLAINS 3",
      "ARTIDOTE",
      "ASHLEY-2",
      "AVENUE PLAINS 4",
      "BEST OF CURTAINS PLAINS 1",
      "BEST OF CURTAINS PLAINS 2",
      "BEST OF CURTAINS PLAINS 3",
      "BEST OF CURTAINS PLAINS 6",
      "BEST OF CURTAINS PLAINS 7",
      "BOTANICA UPHOLSTERY",
      "BRAID",
      "CAMRY",
      "CHARBAGH",
      "CHENOVA",
      "COCOON",
      "COROLLA",
      "COZY 2",
      "CURIO",
      "DEKORAMA",
      "DEVORE 2",
      "ECHO",
      "ELEGANCE DIMOUTS",
      "EVOLUTION",
      "FAUX LEATHER",
      "FRAGMENT TEXTURES",
      "FRAGMENT TEXTURES 2",
      "GLINT",
      "GUSTO",
      "HARDESS",
      "ICONIC",
      "ICONIC BLUSH& TAUPE",
      "ICONIC EMERALD & GOLD",
      "ICONIC SILVER& CHARCOAL",
      "INTERWAVE",
      "IONA",
      "JACKSON",
      "JV 161",
      "KAWA",
      "LOCALE",
      "MACQUEEN",
      "MAGIC -6033",
      "MAGIC 142",
      "MAGIC 200",
      "MAGIC 340",
      "MAGIC 362",
      "MAGIC 5052",
      "MAGIC 6033",
      "MAGIC 6041",
      "MAGIC 6042",
      "MAGIC 7005",
      "MAGIC 7013",
      "MAGIC 7031",
      "MAGIC 7040",
      "MAGIC 7077",
      "MAGIC 713",
      "MAGIC-6082",
      "MALACCA",
      "MATRIC",
      "MAYA",
      "MAYLIN",
      "MEHSANA",
      "MELFORD PLAINS 2",
      "MIKAH",
      "MILANO",
      "MUBUCK",
      "MUSHROOM",
      "NEO",
      "NEW STANLEY",
      "NIMIETY-2",
      "NIOMMI 2",
      "NOAH",
      "NVN CARVE CROCO",
      "NVN ROOT RADICLE",
      "NVN VANILLA",
      "ORNATE",
      "PALAMPORE",
      "PLEATHER",
      "POLO",
      "PORTICO",
      "RAFT-2",
      "RAPTORS",
      "RAYA T3",
      "RHEA 2",
      "RIFANO",
      "RIHANA",
      "SAN MARINO",
      "SANTIAGO 2",
      "SANTIAGO 3",
      "SEDONA",
      "SILVASSA",
      "STANFORD",
      "STARK",
      "SUGAR",
      "TANSY",
      "TESLA",
      "TRENO",
      "UNO",
      "VIDHYUT",
      "WICKER",
      "YALE-2",
      "ZURICH",
      "ZYNA",
    ],
  },
  {
    family: "FLOORING",
    names: [
      "5 MM SPC FLOORING",
      "AC4 GRADE LAMINATE",
      "AGUA",
      "BODHI EXCLUSIVE VINYL FLOORING",
      "BORN IN GERMANY BROUGHT UP GLOBALLY AC 4 GRADE",
      "CLASSIC EUROPEAN SERIES",
      "CLASSIC PREMIUM SERIUS AC4 GRADE 8 MM",
      "DELTA",
      "FRISKY",
      "GYMTEX FLOORING INDIA",
      "HERRINGBONE",
      "HYBRID VINYL PLANKS 3 MM",
      "INNOVA",
      "LEGACY",
      "LUMBER",
      "LUXE",
      "LUXURY VINYL PLANKS 1.5 MM",
      "MARK",
      "SOL EIR SERIOS",
      "SPC CLICK FLOORING",
      "TIMERLAND",
      "VITALITY DELUXE",
      "VITALITY JUMBO",
      "VITALITY STYLE",
      "WAX COATED",
    ],
  },
  {
    family: "CARPET_ROLL",
    names: [
      "ACCORD PLUS",
      "AMBIENCE",
      "AVENUE",
      "BELLE",
      "BIGG BOSS",
      "CANDID-TOPAZ",
      "CLOUD",
      "COMMON GROUND",
      "CRAYON",
      "CRYSTAL",
      "CT APEX",
      "CT ATOM &CONSTANT FLIER",
      "CT PARAGON",
      "CT TRINITY",
      "EXPRESSION",
      "GRANDEUR",
      "HAMILTON",
      "HAZE",
      "LINES",
      "MOON LIGHT",
      "MOON STAR",
      "NEWPORT",
      "OUTLINE",
      "PALO ALTO",
      "PARIS",
      "PASHMINA",
      "PERSTON",
      "PERTH",
      "RAYS",
      "ROYAL HIGHNESS",
      "ROYAL MAJESTY",
      "ROYAL PLUS",
      "ROYAL SATIN",
      "RUNWAY",
      "SILKEY MAX",
      "SILKY MIST",
      "SNUG",
      "STUDIO & ELEMENT",
      "TAHAN",
      "TRIUMPH",
      "URBAN METRO",
      "WINTAGE",
    ],
  },
  {
    family: "RUG",
    names: [
      "ADDRESS",
      "ADOR",
      "ADORN",
      "AMBER",
      "ANTILLES",
      "AVENUE",
      "BARISTA",
      "BROOKLYN",
      "CHESTER",
      "CHOPER -1",
      "CLIFF",
      "COCOON",
      "CORBIT",
      "COZY",
      "DEXTER",
      "DYNASTY",
      "ECLIPSE",
      "ELITE",
      "ESPIRIT",
      "FERRARI",
      "FLEX",
      "HUSKY",
      "INFINITY",
      "ISLA",
      "JORDAN",
      "KIYOSAKI APRICOT",
      "KIYOSAKIVIOLET 1",
      "KIYOSAKIVIOLET 5",
      "LAMA",
      "LOCALE",
      "LUXOR",
      "MISTY COLLECTION",
      "NAUTICA",
      "ORNATE",
      "OXFORD",
      "PAGE 3",
      "PASSPORT",
      "PLEATHER",
      "PLUSH",
      "PORTICO",
      "PUSHPA",
      "RIPPLE",
      "RUMI",
      "RYDER",
      "SOHO",
      "STANLEY-4",
      "STANLEY-5",
      "TESLA",
      "UTOPIA",
    ],
  },
  {
    family: "BLIND",
    names: [
      "BORDER LINE DIMOUT",
      "BROADING LINING",
      "CELLULAR COLLECTION",
      "CLOUDS DIMOUT",
      "CORTINA COLLECTION VOL 1",
      "CORTINA COLLECTION VOL 2",
      "CORTINA COLLECTION VOL 3",
      "COSCO VEGAN LEATHER",
      "DARK HORSE DIMOUT",
      "DIMOUT COLORS",
      "DIMOUT REGULAR",
      "DIMOUT REGULAR (10*6)",
      "FAST TRACK COLLECTION VOL 1",
      "FAST TRACK COLLECTION VOL 2",
      "GRADIANT DIMOUT",
      "HERITAGE (FOAM DIMOUT)",
      "LINING DIMOUT",
      "MARBLE BLACKOUT",
      "MONALISA BLACKOUT",
      "MONOCHROME BLACKOUT",
      "NATURAL BLACKOUT",
      "PARTITION DIMOUT",
      "PYRAMID DIMOUT",
      "SSD",
      "SSD BLACKOUT ROLLER FABRICS VOL 2",
      "SSD DIMOUT&BLACKOUT",
      "SSD ROMAN SHADES",
      "SSD ZEBRA BLINDS",
      "SSG ROLLER COLLECTION",
      "STAR BLACKOUT",
      "SUPER BLACKOUT",
      "TRIPLE BROAD LINE DIMOUT",
      "VISION COLLECTION VOL 1",
      "VISION COLLECTION VOL 2",
      "VISION COLLECTION VOL 3",
      "WIZARD DIMOUT",
      "WONDERFUL BLACKOUT",
    ],
  },
];
