// Entity generator — extracts the Catalog module pattern into a reusable scaffold.
// Usage: pnpm tsx src/generators/generate.ts <moduleName>
// Reads the spec from src/generators/specs/<moduleName>.ts and writes three files:
//   src/modules/<moduleName>/schema.ts
//   src/modules/<moduleName>/actions.ts
//   src/modules/<moduleName>/queries.ts
//
// WHAT THE GENERATOR CANNOT PRODUCE (must be hand-coded):
//   • Complex hierarchical relations (Brand→Collection→Design→Colourway)
//   • Custom search with tsvector / pg_trgm joins
//   • Multi-step transactions (issueSampleBook, setPrice with expiry)
//   • Seam contracts with business logic (getColourwayForQuote)
//   • Row-level field stripping (stripping COST price by role)
//   • Dye-lot capture on GRN, append-only StockMove
//   • Approval workflows (PurchaseRequest)

import { writeFileSync, mkdirSync } from "fs";
import { join } from "path";
import type { EntitySpec, FieldSpec, ModuleSpec } from "./types";

// ── Helpers ───────────────────────────────────────────────────────────────────

function toPascal(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function fieldZod(f: FieldSpec): string {
  let expr = f.zod;
  if (f.optional) expr += ".optional()";
  if (f.nullable) expr += ".nullable()";
  if (f.defaultValue !== undefined) expr += `.default(${f.defaultValue})`;
  return expr;
}

// ── Schema template ───────────────────────────────────────────────────────────

function genSchema(entities: EntitySpec[]): string {
  const blocks = entities.map((e) => {
    const fields = e.fields
      .map((f) => `  ${f.name}: ${fieldZod(f)},`)
      .join("\n");
    const pascal = toPascal(e.name);
    return [
      `export const ${pascal}Schema = z.object({`,
      fields,
      `});`,
      `export type ${pascal}Input = z.infer<typeof ${pascal}Schema>;`,
    ].join("\n");
  });

  return [
    `// Generated by src/generators/generate.ts — do not hand-edit the scaffolding.`,
    `// Add module-specific schemas below the generated block.`,
    `import { z } from "zod";`,
    ``,
    ...blocks,
    ``,
    `// ── Search params (shared) ────────────────────────────────────────────────────`,
    `export const ListParams = z.object({`,
    `  q: z.string().optional(),`,
    `  page: z.number().int().min(1).default(1),`,
    `  pageSize: z.number().int().min(1).max(100).default(30),`,
    `});`,
    `export type ListParamsInput = z.infer<typeof ListParams>;`,
  ].join("\n");
}

// ── Actions template ──────────────────────────────────────────────────────────

function genEntityActions(e: EntitySpec): string {
  const pascal = toPascal(e.name);
  const camel = e.name.charAt(0).toLowerCase() + e.name.slice(1);

  const createFn = [
    `export async function create${pascal}(`,
    `  input: unknown,`,
    `): Promise<ActionResult<{ id: string }>> {`,
    `  const ctx = await devContext();`,
    `  requirePermission(ctx, "${e.createPermission}");`,
    `  const parsed = ${pascal}Schema.safeParse(input);`,
    `  if (!parsed.success) return zodError(parsed.error);`,
    `  const db = scoped(ctx);`,
    `  const row = await db.${camel}.create({`,
    `    data: { organizationId: ctx.orgId, ...parsed.data },`,
    `    select: { id: true },`,
    `  });`,
    `  revalidatePath("${e.revalidatePath}");`,
    `  return { ok: true, data: { id: row.id } };`,
    `}`,
  ].join("\n");

  const updateFn = [
    `export async function update${pascal}(`,
    `  id: string,`,
    `  input: unknown,`,
    `): Promise<ActionResult<{ id: string }>> {`,
    `  const ctx = await devContext();`,
    `  requirePermission(ctx, "${e.updatePermission}");`,
    `  const parsed = ${pascal}Schema.partial().safeParse(input);`,
    `  if (!parsed.success) return zodError(parsed.error);`,
    `  const db = scoped(ctx);`,
    `  const row = await db.${camel}.update({`,
    `    where: { id },`,
    `    data: parsed.data,`,
    `    select: { id: true },`,
    `  });`,
    `  revalidatePath("${e.revalidatePath}");`,
    `  return { ok: true, data: { id: row.id } };`,
    `}`,
  ].join("\n");

  const deleteFn = e.deletePermission
    ? [
        `export async function delete${pascal}(id: string): Promise<ActionResult> {`,
        `  const ctx = await devContext();`,
        `  requirePermission(ctx, "${e.deletePermission}");`,
        `  const db = scoped(ctx);`,
        `  await db.${camel}.delete({ where: { id } });`,
        `  revalidatePath("${e.revalidatePath}");`,
        `  return { ok: true };`,
        `}`,
      ].join("\n")
    : null;

  return [createFn, updateFn, deleteFn].filter(Boolean).join("\n\n");
}

function genActions(entities: EntitySpec[]): string {
  const imports = entities.map((e) => `  ${toPascal(e.name)}Schema,`).join("\n");
  const fnBlocks = entities.map(genEntityActions).join("\n\n");

  return [
    `"use server";`,
    `// Generated by src/generators/generate.ts — do not hand-edit the scaffolding.`,
    `// Add module-specific actions below the generated block.`,
    ``,
    `import { z } from "zod";`,
    `import { revalidatePath } from "next/cache";`,
    `import { scoped } from "@/kernel/db/scoped";`,
    `import { requirePermission } from "@/kernel/rbac/guard";`,
    `import { devContext } from "@/lib/dev-context";`,
    `import {`,
    imports,
    `} from "./schema";`,
    ``,
    `export interface ActionResult<T = unknown> {`,
    `  ok: boolean;`,
    `  data?: T;`,
    `  error?: string;`,
    `  fieldErrors?: Record<string, string[]>;`,
    `}`,
    ``,
    `function zodError<T>(err: z.ZodError): ActionResult<T> {`,
    `  const fieldErrors: Record<string, string[]> = {};`,
    `  for (const issue of err.issues) {`,
    `    const key = issue.path.join(".");`,
    `    (fieldErrors[key] ??= []).push(issue.message);`,
    `  }`,
    `  return { ok: false, error: "Validation failed", fieldErrors };`,
    `}`,
    ``,
    fnBlocks,
  ].join("\n");
}

// ── Queries template ──────────────────────────────────────────────────────────

function genQueries(entities: EntitySpec[]): string {
  const fns = entities.map((e) => {
    const pascal = toPascal(e.name);
    const camel = e.name.charAt(0).toLowerCase() + e.name.slice(1);
    const orderBy = e.orderByField ?? "id";

    const listFn = [
      `export async function list${pascal}s(`,
      `  params: ListParamsInput,`,
      `  ctx: RequestContext,`,
      `) {`,
      `  const db = scoped(ctx);`,
      `  const where = params.q`,
      `    ? { name: { contains: params.q, mode: "insensitive" as const } }`,
      `    : {};`,
      `  const [items, total] = await db.$transaction([`,
      `    db.${camel}.findMany({`,
      `      where,`,
      `      orderBy: { ${orderBy}: "asc" },`,
      `      skip: (params.page - 1) * params.pageSize,`,
      `      take: params.pageSize,`,
      `    }),`,
      `    db.${camel}.count({ where }),`,
      `  ]);`,
      `  return { items, total, page: params.page, pageSize: params.pageSize };`,
      `}`,
    ].join("\n");

    const getFn = [
      `export async function get${pascal}(id: string, ctx: RequestContext) {`,
      `  const db = scoped(ctx);`,
      `  return db.${camel}.findUnique({ where: { id } });`,
      `}`,
    ].join("\n");

    return [listFn, getFn].join("\n\n");
  });

  return [
    `// Generated by src/generators/generate.ts — do not hand-edit the scaffolding.`,
    `// Add module-specific queries below the generated block.`,
    ``,
    `import { scoped } from "@/kernel/db/scoped";`,
    `import type { RequestContext } from "@/kernel/auth/context";`,
    `import type { ListParamsInput } from "./schema";`,
    ``,
    ...fns,
  ].join("\n");
}

// ── Writer ────────────────────────────────────────────────────────────────────

export function generateModule(spec: ModuleSpec): {
  schemaPath: string;
  actionsPath: string;
  queriesPath: string;
} {
  const outDir = join(process.cwd(), "src", "modules", spec.moduleName);
  mkdirSync(outDir, { recursive: true });

  const schemaPath = join(outDir, "schema.ts");
  const actionsPath = join(outDir, "actions.ts");
  const queriesPath = join(outDir, "queries.ts");

  writeFileSync(schemaPath, genSchema(spec.entities), "utf8");
  writeFileSync(actionsPath, genActions(spec.entities), "utf8");
  writeFileSync(queriesPath, genQueries(spec.entities), "utf8");

  return { schemaPath, actionsPath, queriesPath };
}

// ── CLI entry ─────────────────────────────────────────────────────────────────

async function main() {
  const moduleName = process.argv[2];
  if (!moduleName) {
    process.stderr.write("Usage: pnpm tsx src/generators/generate.ts <moduleName>\n");
    process.exit(1);
  }

  const specPath = `./specs/${moduleName}.ts`;
  // Dynamic import so spec files can use TypeScript
  const mod = await import(specPath) as Record<string, unknown>;
  const spec = Object.values(mod).find(
    (v): v is ModuleSpec => typeof v === "object" && v !== null && "moduleName" in v,
  );
  if (!spec) {
    process.stderr.write(`No ModuleSpec export found in ${specPath}\n`);
    process.exit(1);
  }

  const paths = generateModule(spec);
  process.stdout.write(`Generated:\n`);
  for (const p of Object.values(paths)) {
    process.stdout.write(`  ${p}\n`);
  }

  process.stdout.write(`\nDiff vs hand-written Catalog (where generator is worse):\n`);
  process.stdout.write(`  • No tsvector / pg_trgm search — only ILIKE fallback\n`);
  process.stdout.write(`  • No hierarchical relations — single flat entity only\n`);
  process.stdout.write(`  • No multi-step transactions (no issueSampleBook-style ops)\n`);
  process.stdout.write(`  • No seam contracts (no getColourwayForQuote-style API)\n`);
  process.stdout.write(`  • No row-level field stripping by role\n`);
  process.stdout.write(`  • No module-specific pagination enrichment\n`);
  process.stdout.write(`  These gaps must be hand-coded after running the generator.\n`);
}

main().catch((err: unknown) => {
  process.stderr.write(String(err) + "\n");
  process.exit(1);
});
