"use client";

// "Open on phone" QR modal — desktop-only entry point to the field PWA.
// Users on a laptop click this, scan with their phone, and land on
// /m/measure/[projectId] on the device they'll actually measure with
// (spec §4: "Measuring on a laptop at a site is not a real workflow").
//
// The QR image is generated by a public QR-as-service endpoint. The URL
// we encode is the internal `/m/measure` route; nothing sensitive travels
// off the server beyond the app's own public URL, which is deployed
// publicly anyway.

import { X, Copy, Check } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

interface Props {
  projectId: string;
  open: boolean;
  onClose: () => void;
}

export function OpenOnPhoneModal({ projectId, open, onClose }: Props) {
  const [target, setTarget] = useState<string>("");
  const [copied, setCopied] = useState(false);

  // Compute the mobile URL at open time. Prefer NEXT_PUBLIC_APP_URL when
  // set (canonical), otherwise fall back to the browser's origin.
  useEffect(() => {
    if (!open) return;
    const base =
      (typeof process !== "undefined" && process.env["NEXT_PUBLIC_APP_URL"])
      || (typeof window !== "undefined" ? window.location.origin : "");
    setTarget(`${base.replace(/\/$/, "")}/m/measure/${projectId}`);
  }, [open, projectId]);

  const qrSrc = useMemo(() => {
    if (!target) return "";
    return `https://api.qrserver.com/v1/create-qr-code/?size=280x280&margin=8&data=${encodeURIComponent(target)}`;
  }, [target]);

  function copy(): void {
    if (!target) return;
    navigator.clipboard.writeText(target).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    });
  }

  if (!open) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-ink/70 p-4"
      role="dialog"
      aria-modal="true"
      aria-label="Open measurement on phone"
    >
      <div className="w-full max-w-[400px] rounded-[14px] border border-rule bg-surface p-6">
        <div className="mb-1 flex items-baseline justify-between">
          <h2 className="font-display text-[18px] font-semibold text-text">Open on phone</h2>
          <button
            type="button"
            onClick={onClose}
            className="rounded-[6px] p-1 text-text-dim hover:bg-surface-2 hover:text-text"
            aria-label="Close"
          >
            <X size={16} />
          </button>
        </div>
        <p className="mb-4 text-[12px] leading-relaxed text-text-dim">
          Scan with your phone's camera to open the field PWA on this project.
        </p>

        <div className="mb-4 flex items-center justify-center rounded-[10px] border border-rule bg-white p-3">
          {qrSrc ? (
            // Plain <img>: QR is public info generated per-view and the
            // upstream image already runs through api.qrserver.com — no
            // Next Image optimizer benefit for a 280px external asset.
            <img src={qrSrc} alt={`QR code linking to ${target}`} width={280} height={280} />
          ) : (
            <div className="h-[280px] w-[280px] animate-pulse rounded-[6px] bg-surface-2" />
          )}
        </div>

        <div className="flex items-center gap-2 rounded-[8px] border border-rule bg-surface-2 px-3 py-2 text-[11.5px]">
          <span className="min-w-0 flex-1 truncate font-mono text-text-dim">{target}</span>
          <button
            type="button"
            onClick={copy}
            className="inline-flex items-center gap-1 rounded-[6px] px-2 py-1 text-text-dim hover:text-text"
            aria-label="Copy URL"
          >
            {copied ? <Check size={11} className="text-solid" /> : <Copy size={11} />}
            {copied ? "Copied" : "Copy"}
          </button>
        </div>
      </div>
    </div>
  );
}
