"use server";
// Generated by src/generators/generate.ts — do not hand-edit the scaffolding.
// Add module-specific actions below the generated block.

import { z } from "zod";
import { revalidatePath } from "next/cache";
import { scoped } from "@/kernel/db/scoped";
import { requirePermission } from "@/kernel/rbac/guard";
import { devContext } from "@/lib/dev-context";
import {
  VendorSchema,
} from "./schema";

export interface ActionResult<T = unknown> {
  ok: boolean;
  data?: T;
  error?: string;
  fieldErrors?: Record<string, string[]>;
}

function zodError<T>(err: z.ZodError): ActionResult<T> {
  const fieldErrors: Record<string, string[]> = {};
  for (const issue of err.issues) {
    const key = issue.path.join(".");
    (fieldErrors[key] ??= []).push(issue.message);
  }
  return { ok: false, error: "Validation failed", fieldErrors };
}

export async function createVendor(
  input: unknown,
): Promise<ActionResult<{ id: string }>> {
  const ctx = await devContext();
  requirePermission(ctx, "vendor.create");
  const parsed = VendorSchema.safeParse(input);
  if (!parsed.success) return zodError(parsed.error);
  const db = scoped(ctx);
  const row = await db.vendor.create({
    data: { organizationId: ctx.orgId, ...parsed.data },
    select: { id: true },
  });
  revalidatePath("/purchase");
  return { ok: true, data: { id: row.id } };
}

export async function updateVendor(
  id: string,
  input: unknown,
): Promise<ActionResult<{ id: string }>> {
  const ctx = await devContext();
  requirePermission(ctx, "vendor.update");
  const parsed = VendorSchema.partial().safeParse(input);
  if (!parsed.success) return zodError(parsed.error);
  const db = scoped(ctx);
  const row = await db.vendor.update({
    where: { id },
    data: parsed.data,
    select: { id: true },
  });
  revalidatePath("/purchase");
  return { ok: true, data: { id: row.id } };
}