// Generated by src/generators/generate.ts — do not hand-edit the scaffolding.
// Add module-specific queries below the generated block.

import { scoped } from "@/kernel/db/scoped";
import type { RequestContext } from "@/kernel/auth/context";
import type { ListParamsInput } from "./schema";

export async function listVendors(
  params: ListParamsInput,
  ctx: RequestContext,
) {
  const db = scoped(ctx);
  const where = params.q
    ? { name: { contains: params.q, mode: "insensitive" as const } }
    : {};
  const [items, total] = await db.$transaction([
    db.vendor.findMany({
      where,
      orderBy: { name: "asc" },
      skip: (params.page - 1) * params.pageSize,
      take: params.pageSize,
    }),
    db.vendor.count({ where }),
  ]);
  return { items, total, page: params.page, pageSize: params.pageSize };
}

export async function getVendor(id: string, ctx: RequestContext) {
  const db = scoped(ctx);
  return db.vendor.findUnique({ where: { id } });
}