// Generated by src/generators/generate.ts — do not hand-edit the scaffolding.
// Add module-specific schemas below the generated block.
import { z } from "zod";

export const VendorSchema = z.object({
  code: z.string().min(1).max(60),
  name: z.string().min(1).max(120),
  gstin: z.string().max(15).optional().nullable(),
  mobile: z.string().min(10).max(15),
  email: z.string().email().optional().nullable(),
  address: z.record(z.string(), z.unknown()).optional(),
  paymentTermsDays: z.number().int().min(0).max(365).default(30),
  leadTimeDays: z.number().int().min(0).max(365).default(14),
  brandIds: z.array(z.string()).default([]),
  rating: z.number().int().min(1).max(5).optional().nullable(),
});
export type VendorInput = z.infer<typeof VendorSchema>;

// ── Search params (shared) ────────────────────────────────────────────────────
export const ListParams = z.object({
  q: z.string().optional(),
  page: z.number().int().min(1).default(1),
  pageSize: z.number().int().min(1).max(100).default(30),
});
export type ListParamsInput = z.infer<typeof ListParams>;