// Parse the four "real stock" sheets from the wallpaper stock workbook
// into a hand-checkable TS constant we can commit + ship to prod.
//
// The workbook itself doesn't get committed (it's the user's file). Only
// the extracted rows land in src/modules/stock-import/data.ts.

import * as XLSX from "xlsx";
import * as fs from "node:fs";
import * as path from "node:path";

const SRC = "c:/Users/Administrator/Downloads/product catalog/WALLAPPER STOCK LIST (2) (2) (4).xlsx";

interface StockRow {
  family:     "WALLPAPER" | "FLOORING" | "HARDWARE_TRACK";
  brand:      string;                 // brand name (created / reused)
  collection: string;                 // collection name (created / reused)
  code:       string;                 // Design.code
  name:       string;                 // Design.name (default = code)
  sellUnit:   "ROLL" | "BOX" | "PIECE";
  quantity:   number;                 // whole units
  notes?:     string;
}

function parseIntSafe(v: unknown): number {
  if (v == null) return 0;
  const s = String(v).trim();
  // "10 BOX" -> 10, "6" -> 6
  const m = s.match(/^(\d+(?:\.\d+)?)/);
  return m ? Math.round(parseFloat(m[1]!)) : 0;
}

const wb = XLSX.readFile(SRC);
const out: StockRow[] = [];

// 1) MANDOVARA STOCK — wallpaper with catalogue names
{
  const rows = XLSX.utils.sheet_to_json<Record<string, unknown>>(
    wb.Sheets["MANDOVARA STOCK"]!,
    { defval: null, raw: false },
  );
  for (const r of rows) {
    const collection = String(r["CATALOGUE NAME"] ?? "").trim();
    const code       = String(r["CODE NO"] ?? "").trim();
    const qty        = parseIntSafe(r["QUANTITY(ROLLS)"]);
    if (!collection || !code || qty <= 0) continue;
    out.push({
      family:     "WALLPAPER",
      brand:      "Mandovara",
      collection,
      code,
      name:       code,
      sellUnit:   "ROLL",
      quantity:   qty,
    });
  }
}

// 2) BRAHMOS 4.8.26 — brahmos wallpaper (no catalogue name column, sheet = collection)
{
  const rows = XLSX.utils.sheet_to_json<Record<string, unknown>>(
    wb.Sheets["BRAHMOS 4.8.26"]!,
    { defval: null, raw: false },
  );
  for (const r of rows) {
    const code = String(r["CODE NO"] ?? "").trim();
    const qty  = parseIntSafe(r["QTY"]);
    if (!code || qty <= 0) continue;
    out.push({
      family:     "WALLPAPER",
      brand:      "Brahmos",
      collection: "Brahmos 04-Aug-2026",
      code,
      name:       code,
      sellUnit:   "ROLL",
      quantity:   qty,
    });
  }
}

// 3) FLOOR TILE 4.8.26 — flooring; each row is a full product description in CODE NO
{
  const rows = XLSX.utils.sheet_to_json<Record<string, unknown>>(
    wb.Sheets["FLOOR TILE 4.8.26"]!,
    { defval: null, raw: false },
  );
  for (const r of rows) {
    const desc = String(r["CODE NO"] ?? "").trim();
    const qty  = parseIntSafe(r["QTY"]);
    if (!desc || qty <= 0) continue;
    // First token is usually the SKU code (e.g. "1505 PVC FLOOR TILE STRIPS 1.5MM")
    const code = desc.split(/\s+/)[0] ?? desc;
    out.push({
      family:     "FLOORING",
      brand:      "Mandovara",
      collection: "Floor Tile 04-Aug-2026",
      code,
      name:       desc,
      sellUnit:   "BOX",
      quantity:   qty,
    });
  }
}

// 4) TRACK STOCK — hardware; ITEM + INCH combine into a code, CHANEEL is qty
{
  const rows = XLSX.utils.sheet_to_json<Record<string, unknown>>(
    wb.Sheets["TRACK STOCK"]!,
    { defval: null, raw: false },
  );
  // ITEM column has null on continuation rows (merged cells effect)
  let currentItem = "";
  for (const r of rows) {
    const itemCell = r["ITEM"] == null ? "" : String(r["ITEM"]).trim();
    if (itemCell) currentItem = itemCell;
    if (!currentItem) continue;
    const inch = String(r["INCH"] ?? "").trim();
    const qty  = parseIntSafe(r["CHANEEL"]);
    if (!inch || qty <= 0) continue;
    const code = `${currentItem.toUpperCase()}-${inch}IN`;
    out.push({
      family:     "HARDWARE_TRACK",
      brand:      "Mandovara",
      collection: "Track Stock",
      code,
      name:       `${currentItem} ${inch} inch`,
      sellUnit:   "PIECE",
      quantity:   qty,
      notes:      "Channel count",
    });
  }
}

const target = path.join(
  process.cwd(),
  "src",
  "modules",
  "stock-import",
  "data.ts",
);
fs.mkdirSync(path.dirname(target), { recursive: true });
fs.writeFileSync(
  target,
  `/* eslint-disable max-lines */
// AUTO-GENERATED by scripts/extract-stock.ts on ${new Date().toISOString()}
// Do not hand-edit. Re-run the script to regenerate.

export interface StockImportRow {
  readonly family:     "WALLPAPER" | "FLOORING" | "HARDWARE_TRACK";
  readonly brand:      string;
  readonly collection: string;
  readonly code:       string;
  readonly name:       string;
  readonly sellUnit:   "ROLL" | "BOX" | "PIECE";
  readonly quantity:   number;
  readonly notes?:     string;
}

export const STOCK_IMPORT_ROWS: readonly StockImportRow[] = ${JSON.stringify(out, null, 2)} as const;
`,
);

const byFamily: Record<string, number> = {};
for (const r of out) byFamily[r.family] = (byFamily[r.family] ?? 0) + 1;
console.log(`wrote ${out.length} rows → ${target}`);
console.log(`by family:`, byFamily);
