/* eslint-disable max-lines */
// AUTO-GENERATED by scripts/extract-stock.ts on 2026-08-26T17:42:43.241Z
// Do not hand-edit. Re-run the script to regenerate.

export interface StockImportRow {
  readonly family:     "WALLPAPER" | "FLOORING" | "HARDWARE_TRACK";
  readonly brand:      string;
  readonly collection: string;
  readonly code:       string;
  readonly name:       string;
  readonly sellUnit:   "ROLL" | "BOX" | "PIECE";
  readonly quantity:   number;
  readonly notes?:     string;
}

export const STOCK_IMPORT_ROWS: readonly StockImportRow[] = [
  {
    "family": "WALLPAPER",
    "brand": "Mandovara",
    "collection": "FAITH",
    "code": "F7047",
    "name": "F7047",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Mandovara",
    "collection": "ATHENA",
    "code": "8057",
    "name": "8057",
    "sellUnit": "ROLL",
    "quantity": 7
  },
  {
    "family": "WALLPAPER",
    "brand": "Mandovara",
    "collection": "FAITH",
    "code": "F7016",
    "name": "F7016",
    "sellUnit": "ROLL",
    "quantity": 1
  },
  {
    "family": "WALLPAPER",
    "brand": "Mandovara",
    "collection": "F&F",
    "code": "HOR809",
    "name": "HOR809",
    "sellUnit": "ROLL",
    "quantity": 2
  },
  {
    "family": "WALLPAPER",
    "brand": "Mandovara",
    "collection": "-",
    "code": "TN83405",
    "name": "TN83405",
    "sellUnit": "ROLL",
    "quantity": 1
  },
  {
    "family": "WALLPAPER",
    "brand": "Mandovara",
    "collection": "OKHILLA",
    "code": "RD3137",
    "name": "RD3137",
    "sellUnit": "ROLL",
    "quantity": 1
  },
  {
    "family": "WALLPAPER",
    "brand": "Mandovara",
    "collection": "-",
    "code": "NO:0044",
    "name": "NO:0044",
    "sellUnit": "ROLL",
    "quantity": 1
  },
  {
    "family": "WALLPAPER",
    "brand": "Mandovara",
    "collection": "FAITH",
    "code": "F7057",
    "name": "F7057",
    "sellUnit": "ROLL",
    "quantity": 1
  },
  {
    "family": "WALLPAPER",
    "brand": "Mandovara",
    "collection": "FLAMES",
    "code": "200-1",
    "name": "200-1",
    "sellUnit": "ROLL",
    "quantity": 1
  },
  {
    "family": "WALLPAPER",
    "brand": "Mandovara",
    "collection": "MODELICA",
    "code": "AMDL211122",
    "name": "AMDL211122",
    "sellUnit": "ROLL",
    "quantity": 3
  },
  {
    "family": "WALLPAPER",
    "brand": "Mandovara",
    "collection": "F&F",
    "code": "DE214102",
    "name": "DE214102",
    "sellUnit": "ROLL",
    "quantity": 1
  },
  {
    "family": "WALLPAPER",
    "brand": "Mandovara",
    "collection": "BEYOND",
    "code": "72008-4",
    "name": "72008-4",
    "sellUnit": "ROLL",
    "quantity": 1
  },
  {
    "family": "WALLPAPER",
    "brand": "Mandovara",
    "collection": "-",
    "code": "EAR301",
    "name": "EAR301",
    "sellUnit": "ROLL",
    "quantity": 1
  },
  {
    "family": "WALLPAPER",
    "brand": "Mandovara",
    "collection": "PASSENGER",
    "code": "TP21202",
    "name": "TP21202",
    "sellUnit": "ROLL",
    "quantity": 3
  },
  {
    "family": "WALLPAPER",
    "brand": "Mandovara",
    "collection": "-",
    "code": "AD138303",
    "name": "AD138303",
    "sellUnit": "ROLL",
    "quantity": 1
  },
  {
    "family": "WALLPAPER",
    "brand": "Mandovara",
    "collection": "MODELICA",
    "code": "AMDL211125",
    "name": "AMDL211125",
    "sellUnit": "ROLL",
    "quantity": 3
  },
  {
    "family": "WALLPAPER",
    "brand": "Mandovara",
    "collection": "-",
    "code": "386-508-47823",
    "name": "386-508-47823",
    "sellUnit": "ROLL",
    "quantity": 1
  },
  {
    "family": "WALLPAPER",
    "brand": "Mandovara",
    "collection": "MAYA",
    "code": "FE611-1",
    "name": "FE611-1",
    "sellUnit": "ROLL",
    "quantity": 1
  },
  {
    "family": "WALLPAPER",
    "brand": "Mandovara",
    "collection": "-",
    "code": "8603-2",
    "name": "8603-2",
    "sellUnit": "ROLL",
    "quantity": 1
  },
  {
    "family": "WALLPAPER",
    "brand": "Mandovara",
    "collection": "-",
    "code": "7252-1",
    "name": "7252-1",
    "sellUnit": "ROLL",
    "quantity": 1
  },
  {
    "family": "WALLPAPER",
    "brand": "Mandovara",
    "collection": "DREAMLAND",
    "code": "D27-1",
    "name": "D27-1",
    "sellUnit": "ROLL",
    "quantity": 1
  },
  {
    "family": "WALLPAPER",
    "brand": "Mandovara",
    "collection": "1",
    "code": "GREY C0LOUR(DARK)",
    "name": "GREY C0LOUR(DARK)",
    "sellUnit": "ROLL",
    "quantity": 1
  },
  {
    "family": "WALLPAPER",
    "brand": "Mandovara",
    "collection": "2",
    "code": "SANDEL COLOUR",
    "name": "SANDEL COLOUR",
    "sellUnit": "ROLL",
    "quantity": 1
  },
  {
    "family": "WALLPAPER",
    "brand": "Mandovara",
    "collection": "3",
    "code": "GREY C0LOUR(LIGHT)",
    "name": "GREY C0LOUR(LIGHT)",
    "sellUnit": "ROLL",
    "quantity": 1
  },
  {
    "family": "WALLPAPER",
    "brand": "Mandovara",
    "collection": "AL259719-A",
    "code": "LEAF DESINGN",
    "name": "LEAF DESINGN",
    "sellUnit": "ROLL",
    "quantity": 1
  },
  {
    "family": "WALLPAPER",
    "brand": "Mandovara",
    "collection": "AL276246-A",
    "code": "TEMPLE DESIGN",
    "name": "TEMPLE DESIGN",
    "sellUnit": "ROLL",
    "quantity": 1
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2113-1",
    "name": "2113-1",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2113-2",
    "name": "2113-2",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2110-2",
    "name": "2110-2",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2110-3",
    "name": "2110-3",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2111-3",
    "name": "2111-3",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2111-4",
    "name": "2111-4",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2110-5",
    "name": "2110-5",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2111-1",
    "name": "2111-1",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2111-2",
    "name": "2111-2",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2103-3",
    "name": "2103-3",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2103-4",
    "name": "2103-4",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2106-4",
    "name": "2106-4",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2106-5",
    "name": "2106-5",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2101-6",
    "name": "2101-6",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2102-1",
    "name": "2102-1",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2102-2",
    "name": "2102-2",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2102-3",
    "name": "2102-3",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2107-5",
    "name": "2107-5",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2108-1",
    "name": "2108-1",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2107-3",
    "name": "2107-3",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2107-4",
    "name": "2107-4",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2108-2",
    "name": "2108-2",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2108-3",
    "name": "2108-3",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2103-1",
    "name": "2103-1",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2103-2",
    "name": "2103-2",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2102-4",
    "name": "2102-4",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2102-5",
    "name": "2102-5",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2101-3",
    "name": "2101-3",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2101-1",
    "name": "2101-1",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2112-3",
    "name": "2112-3",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2112-2",
    "name": "2112-2",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2111-5",
    "name": "2111-5",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2112-1",
    "name": "2112-1",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2112-4",
    "name": "2112-4",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2112-5",
    "name": "2112-5",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2108-4",
    "name": "2108-4",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2108-5",
    "name": "2108-5",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2105-3",
    "name": "2105-3",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2105-4",
    "name": "2105-4",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2113-3",
    "name": "2113-3",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2113-4",
    "name": "2113-4",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2105-1",
    "name": "2105-1",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2105-2",
    "name": "2105-2",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2106-2",
    "name": "2106-2",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2106-3",
    "name": "2106-3",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2104-2",
    "name": "2104-2",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2104-3",
    "name": "2104-3",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2103-5",
    "name": "2103-5",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2104-1",
    "name": "2104-1",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2105-5",
    "name": "2105-5",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2106-1",
    "name": "2106-1",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2104-4",
    "name": "2104-4",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2104-5",
    "name": "2104-5",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2101-4",
    "name": "2101-4",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2101-5",
    "name": "2101-5",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2107-1",
    "name": "2107-1",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2107-2",
    "name": "2107-2",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2113-5",
    "name": "2113-5",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2110-4",
    "name": "2110-4",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2109-1",
    "name": "2109-1",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2109-2",
    "name": "2109-2",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2109-3",
    "name": "2109-3",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2109-4",
    "name": "2109-4",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2109-5",
    "name": "2109-5",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "WALLPAPER",
    "brand": "Brahmos",
    "collection": "Brahmos 04-Aug-2026",
    "code": "2110-1",
    "name": "2110-1",
    "sellUnit": "ROLL",
    "quantity": 6
  },
  {
    "family": "FLOORING",
    "brand": "Mandovara",
    "collection": "Floor Tile 04-Aug-2026",
    "code": "1505",
    "name": "1505 PVC FLOOR TILE STRIPS 1.5MM",
    "sellUnit": "BOX",
    "quantity": 10
  },
  {
    "family": "FLOORING",
    "brand": "Mandovara",
    "collection": "Floor Tile 04-Aug-2026",
    "code": "1506",
    "name": "1506 PVC FLOOR TILE STRIPS 1.5MM",
    "sellUnit": "BOX",
    "quantity": 10
  },
  {
    "family": "FLOORING",
    "brand": "Mandovara",
    "collection": "Floor Tile 04-Aug-2026",
    "code": "1507",
    "name": "1507 PVC FLOOR TILE STRIPS 1.5MM",
    "sellUnit": "BOX",
    "quantity": 5
  },
  {
    "family": "FLOORING",
    "brand": "Mandovara",
    "collection": "Floor Tile 04-Aug-2026",
    "code": "1508",
    "name": "1508 PVC FLOOR TILE STRIPS 1.5MM",
    "sellUnit": "BOX",
    "quantity": 5
  },
  {
    "family": "FLOORING",
    "brand": "Mandovara",
    "collection": "Floor Tile 04-Aug-2026",
    "code": "1509",
    "name": "1509 PVC FLOOR TILE STRIPS 1.5MM",
    "sellUnit": "BOX",
    "quantity": 10
  },
  {
    "family": "FLOORING",
    "brand": "Mandovara",
    "collection": "Floor Tile 04-Aug-2026",
    "code": "1510",
    "name": "1510 PVC FLOOR TILE STRIPS 1.5MM",
    "sellUnit": "BOX",
    "quantity": 7
  },
  {
    "family": "FLOORING",
    "brand": "Mandovara",
    "collection": "Floor Tile 04-Aug-2026",
    "code": "1511",
    "name": "1511 PVC FLOOR TILE STRIPS 1.5MM",
    "sellUnit": "BOX",
    "quantity": 5
  },
  {
    "family": "FLOORING",
    "brand": "Mandovara",
    "collection": "Floor Tile 04-Aug-2026",
    "code": "1512",
    "name": "1512 PVC FLOOR TILE STRIPS 1.5MM",
    "sellUnit": "BOX",
    "quantity": 10
  },
  {
    "family": "FLOORING",
    "brand": "Mandovara",
    "collection": "Floor Tile 04-Aug-2026",
    "code": "1513",
    "name": "1513 PVC FLOOR TILE STRIPS 1.5MM",
    "sellUnit": "BOX",
    "quantity": 10
  },
  {
    "family": "FLOORING",
    "brand": "Mandovara",
    "collection": "Floor Tile 04-Aug-2026",
    "code": "1514",
    "name": "1514 PVC FLOOR TILE STRIPS 1.5MM",
    "sellUnit": "BOX",
    "quantity": 5
  },
  {
    "family": "FLOORING",
    "brand": "Mandovara",
    "collection": "Floor Tile 04-Aug-2026",
    "code": "1515",
    "name": "1515 PVC FLOOR TILE STRIPS 1.5MM",
    "sellUnit": "BOX",
    "quantity": 10
  },
  {
    "family": "FLOORING",
    "brand": "Mandovara",
    "collection": "Floor Tile 04-Aug-2026",
    "code": "1517",
    "name": "1517 PVC FLOOR TILE STRIPS 1.5MM",
    "sellUnit": "BOX",
    "quantity": 10
  },
  {
    "family": "FLOORING",
    "brand": "Mandovara",
    "collection": "Floor Tile 04-Aug-2026",
    "code": "1518",
    "name": "1518 PVC FLOOR TILE STRIPS 1.5MM",
    "sellUnit": "BOX",
    "quantity": 10
  },
  {
    "family": "FLOORING",
    "brand": "Mandovara",
    "collection": "Floor Tile 04-Aug-2026",
    "code": "1519",
    "name": "1519 PVC FLOOR TILE STRIPS 1.5MM",
    "sellUnit": "BOX",
    "quantity": 5
  },
  {
    "family": "FLOORING",
    "brand": "Mandovara",
    "collection": "Floor Tile 04-Aug-2026",
    "code": "1520",
    "name": "1520 PVC FLOOR TILE STRIPS 1.5MM",
    "sellUnit": "BOX",
    "quantity": 10
  },
  {
    "family": "FLOORING",
    "brand": "Mandovara",
    "collection": "Floor Tile 04-Aug-2026",
    "code": "1521",
    "name": "1521 PVC FLOOR TILE STRIPS 1.5MM",
    "sellUnit": "BOX",
    "quantity": 10
  },
  {
    "family": "FLOORING",
    "brand": "Mandovara",
    "collection": "Floor Tile 04-Aug-2026",
    "code": "1522",
    "name": "1522 PVC FLOOR TILE STRIPS 1.5MM",
    "sellUnit": "BOX",
    "quantity": 10
  },
  {
    "family": "FLOORING",
    "brand": "Mandovara",
    "collection": "Floor Tile 04-Aug-2026",
    "code": "1523",
    "name": "1523 PVC FLOOR TILE STRIPS 1.5MM",
    "sellUnit": "BOX",
    "quantity": 10
  },
  {
    "family": "FLOORING",
    "brand": "Mandovara",
    "collection": "Floor Tile 04-Aug-2026",
    "code": "1524",
    "name": "1524 PVC FLOOR TILE STRIPS 1.5MM",
    "sellUnit": "BOX",
    "quantity": 5
  },
  {
    "family": "FLOORING",
    "brand": "Mandovara",
    "collection": "Floor Tile 04-Aug-2026",
    "code": "1572",
    "name": "1572 PVC FLOOR TILE STRIPS 1.5MM",
    "sellUnit": "BOX",
    "quantity": 10
  },
  {
    "family": "HARDWARE_TRACK",
    "brand": "Mandovara",
    "collection": "Track Stock",
    "code": "ROMAN-26IN",
    "name": "ROMAN 26 inch",
    "sellUnit": "PIECE",
    "quantity": 7,
    "notes": "Channel count"
  },
  {
    "family": "HARDWARE_TRACK",
    "brand": "Mandovara",
    "collection": "Track Stock",
    "code": "ROMAN-62IN",
    "name": "ROMAN 62 inch",
    "sellUnit": "PIECE",
    "quantity": 1,
    "notes": "Channel count"
  },
  {
    "family": "HARDWARE_TRACK",
    "brand": "Mandovara",
    "collection": "Track Stock",
    "code": "ROMAN-52IN",
    "name": "ROMAN 52 inch",
    "sellUnit": "PIECE",
    "quantity": 1,
    "notes": "Channel count"
  },
  {
    "family": "HARDWARE_TRACK",
    "brand": "Mandovara",
    "collection": "Track Stock",
    "code": "JAMBO TRACK-66IN",
    "name": "JAMBO TRACK 66 inch",
    "sellUnit": "PIECE",
    "quantity": 2,
    "notes": "Channel count"
  },
  {
    "family": "HARDWARE_TRACK",
    "brand": "Mandovara",
    "collection": "Track Stock",
    "code": "JAMBO TRACK-67IN",
    "name": "JAMBO TRACK 67 inch",
    "sellUnit": "PIECE",
    "quantity": 2,
    "notes": "Channel count"
  },
  {
    "family": "HARDWARE_TRACK",
    "brand": "Mandovara",
    "collection": "Track Stock",
    "code": "GOLD RAD-64IN",
    "name": "GOLD RAD 64 inch",
    "sellUnit": "PIECE",
    "quantity": 2,
    "notes": "Channel count"
  },
  {
    "family": "HARDWARE_TRACK",
    "brand": "Mandovara",
    "collection": "Track Stock",
    "code": "M TRACK-76IN",
    "name": "M TRACK 76 inch",
    "sellUnit": "PIECE",
    "quantity": 1,
    "notes": "Channel count"
  },
  {
    "family": "HARDWARE_TRACK",
    "brand": "Mandovara",
    "collection": "Track Stock",
    "code": "M TRACK-85.5IN",
    "name": "M TRACK 85.5 inch",
    "sellUnit": "PIECE",
    "quantity": 1,
    "notes": "Channel count"
  },
  {
    "family": "HARDWARE_TRACK",
    "brand": "Mandovara",
    "collection": "Track Stock",
    "code": "M TRACK-82IN",
    "name": "M TRACK 82 inch",
    "sellUnit": "PIECE",
    "quantity": 2,
    "notes": "Channel count"
  },
  {
    "family": "HARDWARE_TRACK",
    "brand": "Mandovara",
    "collection": "Track Stock",
    "code": "M TRACK-26IN",
    "name": "M TRACK 26 inch",
    "sellUnit": "PIECE",
    "quantity": 1,
    "notes": "Channel count"
  },
  {
    "family": "HARDWARE_TRACK",
    "brand": "Mandovara",
    "collection": "Track Stock",
    "code": "ROSE GOLD ROD-41.5IN",
    "name": "ROSE GOLD ROD 41.5 inch",
    "sellUnit": "PIECE",
    "quantity": 1,
    "notes": "Channel count"
  },
  {
    "family": "HARDWARE_TRACK",
    "brand": "Mandovara",
    "collection": "Track Stock",
    "code": "ROSE GOLD ROD-39IN",
    "name": "ROSE GOLD ROD 39 inch",
    "sellUnit": "PIECE",
    "quantity": 1,
    "notes": "Channel count"
  },
  {
    "family": "HARDWARE_TRACK",
    "brand": "Mandovara",
    "collection": "Track Stock",
    "code": "ROSE GOLD ROD-34IN",
    "name": "ROSE GOLD ROD 34 inch",
    "sellUnit": "PIECE",
    "quantity": 1,
    "notes": "Channel count"
  },
  {
    "family": "HARDWARE_TRACK",
    "brand": "Mandovara",
    "collection": "Track Stock",
    "code": "ROSE GOLD ROD-38IN",
    "name": "ROSE GOLD ROD 38 inch",
    "sellUnit": "PIECE",
    "quantity": 1,
    "notes": "Channel count"
  },
  {
    "family": "HARDWARE_TRACK",
    "brand": "Mandovara",
    "collection": "Track Stock",
    "code": "ROSE GOLD ROD-35IN",
    "name": "ROSE GOLD ROD 35 inch",
    "sellUnit": "PIECE",
    "quantity": 1,
    "notes": "Channel count"
  },
  {
    "family": "HARDWARE_TRACK",
    "brand": "Mandovara",
    "collection": "Track Stock",
    "code": "ROSE GOLD ROD-36IN",
    "name": "ROSE GOLD ROD 36 inch",
    "sellUnit": "PIECE",
    "quantity": 1,
    "notes": "Channel count"
  },
  {
    "family": "HARDWARE_TRACK",
    "brand": "Mandovara",
    "collection": "Track Stock",
    "code": "ROSE GOLD ROD-37IN",
    "name": "ROSE GOLD ROD 37 inch",
    "sellUnit": "PIECE",
    "quantity": 1,
    "notes": "Channel count"
  },
  {
    "family": "HARDWARE_TRACK",
    "brand": "Mandovara",
    "collection": "Track Stock",
    "code": "ROSE GOLD ROD-51IN",
    "name": "ROSE GOLD ROD 51 inch",
    "sellUnit": "PIECE",
    "quantity": 1,
    "notes": "Channel count"
  },
  {
    "family": "HARDWARE_TRACK",
    "brand": "Mandovara",
    "collection": "Track Stock",
    "code": "COPPER ROD-39IN",
    "name": "COPPER ROD 39 inch",
    "sellUnit": "PIECE",
    "quantity": 4,
    "notes": "Channel count"
  },
  {
    "family": "HARDWARE_TRACK",
    "brand": "Mandovara",
    "collection": "Track Stock",
    "code": "COPPER ROD-48IN",
    "name": "COPPER ROD 48 inch",
    "sellUnit": "PIECE",
    "quantity": 2,
    "notes": "Channel count"
  },
  {
    "family": "HARDWARE_TRACK",
    "brand": "Mandovara",
    "collection": "Track Stock",
    "code": "COPPER ROD-23IN",
    "name": "COPPER ROD 23 inch",
    "sellUnit": "PIECE",
    "quantity": 1,
    "notes": "Channel count"
  },
  {
    "family": "HARDWARE_TRACK",
    "brand": "Mandovara",
    "collection": "Track Stock",
    "code": "COPPER ROD-54IN",
    "name": "COPPER ROD 54 inch",
    "sellUnit": "PIECE",
    "quantity": 2,
    "notes": "Channel count"
  },
  {
    "family": "HARDWARE_TRACK",
    "brand": "Mandovara",
    "collection": "Track Stock",
    "code": "SS ROD-48IN",
    "name": "SS ROD 48 inch",
    "sellUnit": "PIECE",
    "quantity": 1,
    "notes": "Channel count"
  },
  {
    "family": "HARDWARE_TRACK",
    "brand": "Mandovara",
    "collection": "Track Stock",
    "code": "SS ROD-27IN",
    "name": "SS ROD 27 inch",
    "sellUnit": "PIECE",
    "quantity": 1,
    "notes": "Channel count"
  },
  {
    "family": "HARDWARE_TRACK",
    "brand": "Mandovara",
    "collection": "Track Stock",
    "code": "SS ROD-55IN",
    "name": "SS ROD 55 inch",
    "sellUnit": "PIECE",
    "quantity": 1,
    "notes": "Channel count"
  },
  {
    "family": "HARDWARE_TRACK",
    "brand": "Mandovara",
    "collection": "Track Stock",
    "code": "ANTICRAFF-32IN",
    "name": "ANTICRAFF 32 inch",
    "sellUnit": "PIECE",
    "quantity": 1,
    "notes": "Channel count"
  },
  {
    "family": "HARDWARE_TRACK",
    "brand": "Mandovara",
    "collection": "Track Stock",
    "code": "ANTICRAFF-33IN",
    "name": "ANTICRAFF 33 inch",
    "sellUnit": "PIECE",
    "quantity": 1,
    "notes": "Channel count"
  },
  {
    "family": "HARDWARE_TRACK",
    "brand": "Mandovara",
    "collection": "Track Stock",
    "code": "SST HEAVY CHANEL-57.5IN",
    "name": "SST HEAVY CHANEL 57.5 inch",
    "sellUnit": "PIECE",
    "quantity": 1,
    "notes": "Channel count"
  },
  {
    "family": "HARDWARE_TRACK",
    "brand": "Mandovara",
    "collection": "Track Stock",
    "code": "BLACK ROD-92IN",
    "name": "BLACK ROD 92 inch",
    "sellUnit": "PIECE",
    "quantity": 1,
    "notes": "Channel count"
  }
] as const;
